import { createHash, randomBytes } from 'node:crypto';
import type { AppConfig } from '../config/schema.js';

/**
 * The invitation token: minted here, stored only as a hash, and delivered
 * exactly once — in the email.
 *
 * ── Why the token exists at all ────────────────────────────────────────────
 * Without it, the only thing binding an invited person to the membership
 * somebody created for them would be an EMAIL MATCH in `POST /auth/session`
 * path 2. An invitee who signed in with a different address than the one typed
 * would fall through to path 4 instead — a `403 no_membership` — while their real
 * membership sat unclaimed and nothing told anybody. The token replaces that match: possession of a link delivered to the invited
 * inbox is the authority, and the address the person signs in with becomes a
 * fact to record rather than a key to resolve by.
 */

/**
 * Bytes of entropy per token, before encoding.
 *
 * 32 bytes = 256 bits, which is the same order as the hash it is stored under
 * and far beyond anything the rate limiter on `/invites/*` would ever let an
 * attacker walk. The number that actually matters is not this one though — it is
 * that the token is generated by `randomBytes`, a CSPRNG, and not by
 * `Math.random`, `Date.now()` or a UUIDv4 whose non-random bits are structural.
 * A guessable invite token is account takeover for the membership it names.
 */
const TOKEN_BYTES = 32;

/**
 * `base64url`, not `hex` and not plain `base64`.
 *
 * The token travels in a URL PATH (`/agency/join/:token`) and in an email body
 * that mail clients will linkify. `base64url` has no `+`, `/` or `=`, so nothing
 * needs percent-encoding, nothing is mangled by a client that stops the link at
 * a `+`, and the value survives a copy-paste out of a plain-text part. `hex`
 * would be safe too but doubles the length for the same entropy, and a long
 * token is the thing that gets line-wrapped in a text email and broken.
 */
const TOKEN_ENCODING = 'base64url' as const;

/**
 * Config, resolved on first use rather than on import — the same lazy pattern,
 * for the same reason, as `invite-mailer.ts`.
 *
 * `src/config/index.ts` runs `loadConfig()` at module scope and calls
 * `process.exit(1)` when the Zod schema does not parse. This module is imported
 * by `user.routes.ts`, whose integration suite mocks every module that touches
 * config; a STATIC import here would drag that process-killing side effect into
 * the import graph of that suite and fail it at `invite-token.ts:1:1`, with no
 * reference to invites anywhere in the failure. That is not hypothetical — it is
 * exactly what happened when `invite-mailer.ts` first imported config directly.
 */
let cachedConfig: AppConfig | undefined;
async function appConfig(): Promise<AppConfig> {
  if (!cachedConfig) {
    ({ config: cachedConfig } = await import('../config/index.js'));
  }
  return cachedConfig;
}

/**
 * The configured TTL in days. There is deliberately NO local fallback.
 *
 * This module used to export a `DEFAULT_INVITE_TTL_DAYS = 7` whose docstring —
 * and a matching claim on `invitesSchema.tokenTtlDays` — said it existed so the
 * module "must have an answer even in the failure case where config cannot be
 * read at all". Neither half was true: nothing referenced the constant, and this
 * function has never had a fallback. It simply awaits config and lets a failure
 * propagate.
 *
 * Making the code match the docstring was the wrong repair, so the docstring
 * went instead. `loadConfig()` already fails CLOSED — `src/config/index.ts` calls
 * `process.exit(1)` on a schema that does not parse — so the "config cannot be
 * read" case cannot reach a running server, and a local `?? 7` here would only
 * ever fire on a genuinely broken deployment, where it would mint credentials
 * against a TTL nobody configured and hide the misconfiguration behind a
 * plausible number. `invitesSchema.tokenTtlDays`'s `.default(7)` is now the one
 * place the seven days is written, which also removes the drift the deleted
 * constant claimed to prevent while being the second copy of it.
 *
 * A caller that must not depend on config passes an explicit `ttlDays` to
 * {@link mintInviteToken} — the same short-circuit `inviteSignInUrl`'s `baseUrl`
 * parameter provides, and the reason the mint/hash/expiry rule is testable with
 * no config module at all.
 */
export async function inviteTokenTtlDays(): Promise<number> {
  return (await appConfig()).invites.tokenTtlDays;
}

/**
 * `sha256(token)`, hex — the ONLY form of the token that is ever persisted.
 *
 * ── Why the raw token is not stored ────────────────────────────────────────
 * `membership_invites.token_hash` is a credential in the same sense a password
 * is: a row that held the token itself would let anyone with a database dump —
 * a backup, a read replica, a support export, a leaked snapshot — walk straight
 * into every outstanding membership. Storing the hash means the dump contains
 * nothing replayable, and the raw value exists in exactly one place: the email
 * that carried it.
 *
 * ── Why NO constant-time comparison, and why that is not an oversight ───────
 * The usual rule for verifying a secret is `timingSafeEqual`, because comparing
 * a stored secret against a supplied one byte-by-byte leaks how many bytes
 * matched, and an attacker can walk the secret one byte at a time.
 *
 * That attack needs an ORACLE that compares a candidate against a KNOWN target.
 * There is none here. Verification is not a comparison at all: the supplied
 * token is hashed and the hash is handed to Postgres as an equality lookup on a
 * unique index over the whole table. There is no "the" secret to walk toward,
 * the timing of a B-tree probe is a function of the index rather than of how
 * many leading bytes agree, and — decisively — a byte-at-a-time attack would
 * have to walk the SHA-256 of the token, which cannot be inverted into the token
 * the attacker actually needs to send.
 *
 * So the protection here is the hash-then-index lookup, not a comparison
 * primitive, and reaching for `timingSafeEqual` would be a comparison that does
 * not exist to make. What DOES matter, and is easy to lose: the lookup must stay
 * `WHERE token_hash = $1`. Reintroducing any per-row comparison in JavaScript —
 * fetching candidates and scanning them — would create the oracle this note says
 * we do not have.
 */
export function hashInviteToken(token: string): string {
  return createHash('sha256').update(token, 'utf8').digest('hex');
}

/** A freshly minted token and everything the row needs to store it. */
export interface MintedInviteToken {
  /**
   * The raw token. Goes in the email and NOWHERE else — never a log line, never
   * a response body other than the join URL itself, never an audit `details`
   * field. It is the credential.
   */
  token: string;
  /** What `membership_invites.token_hash` stores. */
  tokenHash: string;
  /** What `membership_invites.expires_at` stores. */
  expiresAt: Date;
}

/**
 * Mint a token and its expiry.
 *
 * `ttlDays` overrides the configured TTL, which is what lets the whole mint /
 * hash / expiry rule be tested without a config module at all — the same
 * short-circuit `inviteSignInUrl`'s `baseUrl` parameter provides, and for the
 * same reason.
 */
export async function mintInviteToken(ttlDays?: number): Promise<MintedInviteToken> {
  const days = ttlDays ?? (await inviteTokenTtlDays());
  const token = randomBytes(TOKEN_BYTES).toString(TOKEN_ENCODING);
  return {
    token,
    tokenHash: hashInviteToken(token),
    // Computed here rather than as a Postgres `NOW() + interval`, so the value
    // that goes in the row is the same instant the email's small print states.
    // Two clocks producing two answers for one invitation is the kind of
    // one-minute discrepancy that turns into a support thread nobody can close.
    expiresAt: new Date(Date.now() + days * 24 * 60 * 60 * 1000),
  };
}

/**
 * Is this invitation past its expiry, as of `now`?
 *
 * A function rather than an inline comparison at the two call sites, because
 * both of them (`GET /invites/:token` reporting a status, and the claim refusing
 * one) must agree exactly. A page that says "expired" while the claim still
 * accepts it — or the reverse — is worse than either answer alone.
 */
export function isInviteExpired(expiresAt: Date, now: Date = new Date()): boolean {
  return expiresAt.getTime() <= now.getTime();
}
